version: '3.3'

services:
  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: whois
    volumes:
      - "mariadb_data:/var/lib/mysql"

  mirror:
    depends_on:
      - db
    image: ripe-mirror:latest
    restart: always
    ports:
      - 127.0.0.8:1043:1043
      - 127.0.0.8:1080:1080
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PWD: whois
    volumes:
      - "./whois.properties:/app/properties:ro"
      - "mirror_data:/app/var"

volumes:
  mariadb_data: {}
  mirror_data: {}